Server=.\SQLEXPRESS;Database=SeedECommerce;Integrated Security=True;


Server=localhost\\SQLEXPRESS;Database=SportsStore;Trusted_Connection=True;MultipleActiveResultSets=true;TrustServerCertificate=True;

dotnet ef dbcontext scaffold Name=MyDatabaseConnection Microsoft.EntityFrameworkCore.SqlServer -o Models

